### PR TITLE
- fixes #17, #22, #24, #28: bumps dependencies so IAuthenticationProv…

### LINKED ISSUE #17: [ERROR] class file for com.microsoft.graph.httpcore.IAuthenticationProvider not found
Please update maven snapshot. There is an issue. Instead of fixed microsoft-graph-auth-0.1.0-SNAPSHOT.jar maven downloads affected microsoft-graph-auth-0.1.0-20190227.065917-1.jar.

### PR DESCRIPTION
**Pull request by baywet**
…ider and ICoreAuthenticationProvider can be found

fixes #17, #22, #24, #28, #20

### CODE REVIEW

**Comment by vtiwari227** [comment]
@baywet  when this PR will be merged ? It's blocking our workflow to authenticate with java graph client ? thanks

**Comment by baywet** [comment]
@vtiwari227 I'm not sure, I don't have contrib permissions on that repo. @darrelmiller ?

**Comment by ddyett** [comment]
@darrelmiller  yes i'll put someone on it.

**Comment by baywet** [comment]
Thanks @MIchaelMainer !! for some reason only the first issue was closed, can you close these ones as well please?  #22, #24, #28, #20

**Comment by baywet** [comment]
and close #30 that's a duplicate of this PR

**Pull request merged**
